language: node_js
node_js: 
  "12"

jobs:
  include:
    - stage: dependencies
    - script: npm install -g firebase-tools
    - script: npm install -g @angular/cli
    - stage: build
    - script: npm run build
    - stage: deploy
    - script: firebase deploy --token $FIREBASE_TOKEN
    
stages:
  - dependencies
  - build
  - name: deploy
    if: branch = master
