language: node_js
node_js: '10.16'
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: hCWTdkvZBlEaTk5GXTg51b9yZDUyf4h94G/b5UMPPsR4t+DCHdgAhAo7FiHK/+Mbok8n2sdICkLZE70JhhsJDgG80DjErPjdBOGXfIDbPwmLwYNErP7lrFbirSQNs+ez4PAsWQIiHtUVXmpUmgB9L9RMXWpcMpAHh2u8FVfpohPrGrrvseHWM6hf3KZSyIhUpIlObzYkPC+9uDYO+Wo7Bdx2UKmLEDGrykf4213238dI1HDLf9XNAzsI9yQmhpV7myMiU71KGYJzkUNek+IRB0jm239X7io3b/HjlnSrLtDQtqNRSMHGoZT8le1vYzJIGMLlGuP/YjcDXhbew4PCzsSYNa3S6qilmTb6e2nxcI9DJm1JVIM1G9eAnC1T8g3Z+0FtAWmQ+slJPjZ0vVALs+Y9DOobP0C27ztN1TgO8N2y86x6CEeUlTrVi8pha92ohU2pgthtj5nIn/0VM1aicJBbQ6RVOTLqGnlJC5LvTS/nDRYwITyKr4PGOMcBE/KIBUWqvSkK+gvFeBlinra/YMAgv4J/3Bd5ygt6PG6Vt8faLgscZRzAxBqyXYMTs0EjzKMxN6dwbttJ9cEwNGY2/IcOd4Py4saLidFwq6VgpnQjCMBRCNHFZW/e3rDHBOzz1QOUXPG8X1DvRrcZunYvwRFNNUAHFe+hMtJafOaV1a0=
