language: node_js
node_js: 
  "10.16"
  
branches:
  only:
  - master

script:
- npm run build

deploy:
  provider: firebase
  token:
    secure: "RDLCZbtWav9JMvEQYQ06zTmJ0v/Wsrt063XICKjn5LevjQ45sEAzE936NvxauMWMsrcRfb4IqVKEoVEEk4xiLjgtMCfRcb6xsCyMGVwFGxAuQSDGAXsktxUoZtyofEoOtU+w0HF8ishDBW3aQfqBg9Gbe6E7oYNRH0tepcGEzlR2DfWP7RpTW3zGDYHXun+kZXvLYdKc/3loYuvpPEZGxp6Cp7d/FeyCo+mCDl+vHne8+zRTYBeMOVW9ohdrJ6w84qicxzazacfg49YlPZuS9jJLDIJFoRlxtuZTlMRUTRrtqgfa7Mh7wBtfqLXWIT7p4R/hScKhDkH8jfemmtiDtNppBk94AnX+PPWm5ltWjV/2Y1M6kpk3GNAUp8C1XpC9LXNtKy+N1lKwmgje0HgZNsmZTqy1xupq7iMrBF8lmd3ioVWRsUa77WwcN4idTNmL4HIBLHfAvmYQnaLBfovLcS6Msfoeo9n7Yj8MBrlhNU7l1FfBWs1rAktBtyJzT+82g6jJC3o4IPhPP5PAQ1khsSO5TPjmJtCX20no4x/9nxZeRPrOsbOX1SF57HHPCUR6TfBVNrEk1/CoOgTGJvjjFUEwzqUdS4jLc/KJJuYE3P7gLbNua/GPv3GZa5whRiwlX+xQVe9itQlUNwRHr2PFITr1E4BHk7IUa5pkPLjw2RA="
