language: node_js
node_js: 
  "11"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
   
jobs:
  include:
    - stage: build
    - script: npm run build
    - stage: deploy
    - script: 
      - npm install -g @angular/cli
      - npm install -g firebase-tools
      - firebase deploy --token $FIREBASE_TOKEN
    
stages:
  - build
  - name: deploy
    if: branch = master AND type = push
